services:
  app:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://mongodb:27017/transport
    ports:
      - '5001:5000'
#    command: "entrypoint.sh"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27020:27017'
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata: